### PR TITLE
Animation

### PR DESCRIPTION
**Pull request by otavio**

### CODE REVIEW

**Comment by otavio** [comment]
@lucasdemarchi I think this is ready for your review. Please take a look and let @gustavosbarreto and I know about any issues.

We hope to get some more improvements send soon.

**Comment by gustavosbarreto** [comment]
Lucas, fiz as correções no commit

**Comment by walkthetalk** [comment]
Great!!!
I'm using it in poky environment, maybe we can integrate it into poky.
and another problem is font, maybe we can provide an simple bitmap font.

I know it just for English, or it can't keep lightweight.

I'm using Chinese, so I must convert some string(e.g. version number) to bitmap on pc for every release.

**Comment by otavio** [comment]
We ended writing a new splash system we are using at O.S. Systems' projects. The diedsplash works fine for simple framebuffer systems but its code was difficult to adapt to other backends (we ended adding GLES2, Vivante G2D and others in our one).

**Comment by lucasdemarchi** [comment]
@otavio  is it opensource?

**Comment by otavio** [comment]
Not for now.

**Pull request closed without merging**
